// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UpCloud.Pulumi.UpCloud.Inputs
{

    public sealed class GatewayConnectionRemoteRouteArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name of the route
        /// </summary>
        [Input("name", required: true)]
        public Input<string> Name { get; set; } = null!;

        /// <summary>
        /// Destination prefix of the route; needs to be a valid IPv4 prefix
        /// </summary>
        [Input("staticNetwork", required: true)]
        public Input<string> StaticNetwork { get; set; } = null!;

        /// <summary>
        /// Type of route; currently the only supported type is 'static'
        /// </summary>
        [Input("type")]
        public Input<string>? Type { get; set; }

        public GatewayConnectionRemoteRouteArgs()
        {
        }
        public static new GatewayConnectionRemoteRouteArgs Empty => new GatewayConnectionRemoteRouteArgs();
    }
}
