// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UpCloud.Pulumi.UpCloud.Inputs
{

    public sealed class ManagedDatabaseOpensearchNodeStateArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Name plus a node iteration
        /// </summary>
        [Input("name")]
        public Input<string>? Name { get; set; }

        /// <summary>
        /// Role of the node
        /// </summary>
        [Input("role")]
        public Input<string>? Role { get; set; }

        /// <summary>
        /// Current state of the node
        /// </summary>
        [Input("state")]
        public Input<string>? State { get; set; }

        public ManagedDatabaseOpensearchNodeStateArgs()
        {
        }
        public static new ManagedDatabaseOpensearchNodeStateArgs Empty => new ManagedDatabaseOpensearchNodeStateArgs();
    }
}
