// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UpCloud.Pulumi.UpCloud.Inputs
{

    public sealed class ServerFirewallRulesFirewallRuleArgs : global::Pulumi.ResourceArgs
    {
        /// <summary>
        /// Action to take if the rule conditions are met. Valid values `accept | drop`.
        /// </summary>
        [Input("action", required: true)]
        public Input<string> Action { get; set; } = null!;

        /// <summary>
        /// A comment for the rule.
        /// </summary>
        [Input("comment")]
        public Input<string>? Comment { get; set; }

        /// <summary>
        /// The destination address range ends from this address
        /// </summary>
        [Input("destinationAddressEnd")]
        public Input<string>? DestinationAddressEnd { get; set; }

        /// <summary>
        /// The destination address range starts from this address
        /// </summary>
        [Input("destinationAddressStart")]
        public Input<string>? DestinationAddressStart { get; set; }

        /// <summary>
        /// The destination port range ends from this port number
        /// </summary>
        [Input("destinationPortEnd")]
        public Input<string>? DestinationPortEnd { get; set; }

        /// <summary>
        /// The destination port range starts from this port number
        /// </summary>
        [Input("destinationPortStart")]
        public Input<string>? DestinationPortStart { get; set; }

        /// <summary>
        /// The direction of network traffic this rule will be applied to. Valid values are `In` and `Out`.
        /// </summary>
        [Input("direction", required: true)]
        public Input<string> Direction { get; set; } = null!;

        /// <summary>
        /// The address family of new firewall rule
        /// </summary>
        [Input("family")]
        public Input<string>? Family { get; set; }

        /// <summary>
        /// The ICMP type of the rule. Only valid if protocol is ICMP.
        /// </summary>
        [Input("icmpType")]
        public Input<string>? IcmpType { get; set; }

        /// <summary>
        /// The protocol of the rule. Possible values are `` (empty), `Tcp`, `Udp`, `Icmp`.
        /// </summary>
        [Input("protocol")]
        public Input<string>? Protocol { get; set; }

        /// <summary>
        /// The source address range ends from this address
        /// </summary>
        [Input("sourceAddressEnd")]
        public Input<string>? SourceAddressEnd { get; set; }

        /// <summary>
        /// The source address range starts from this address
        /// </summary>
        [Input("sourceAddressStart")]
        public Input<string>? SourceAddressStart { get; set; }

        /// <summary>
        /// The source port range ends from this port number
        /// </summary>
        [Input("sourcePortEnd")]
        public Input<string>? SourcePortEnd { get; set; }

        /// <summary>
        /// The source port range starts from this port number
        /// </summary>
        [Input("sourcePortStart")]
        public Input<string>? SourcePortStart { get; set; }

        public ServerFirewallRulesFirewallRuleArgs()
        {
        }
        public static new ServerFirewallRulesFirewallRuleArgs Empty => new ServerFirewallRulesFirewallRuleArgs();
    }
}
