# See default values from https://github.com/pulumi/ci-mgmt/blob/master/provider-ci/internal/pkg/templates/defaults.config.yaml

lint: true
major-version: 0
organization: UpCloudLtd
provider: upcloud
providerDefaultBranch: main
publishRegistry: false # TODO: update after the first release to Pulumi registry
publish:
  sdk: all,!java
  cdn: false
upstreamProviderOrg: UpCloudLtd
upstream-provider-repo: terraform-provider-upcloud
