// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class FileStorageShareAcl {
    /**
     * @return Access level: &#39;ro&#39; or &#39;rw&#39;.
     * 
     */
    private String permission;
    /**
     * @return Target IP/CIDR or &#39;*&#39;.
     * 
     */
    private String target;

    private FileStorageShareAcl() {}
    /**
     * @return Access level: &#39;ro&#39; or &#39;rw&#39;.
     * 
     */
    public String permission() {
        return this.permission;
    }
    /**
     * @return Target IP/CIDR or &#39;*&#39;.
     * 
     */
    public String target() {
        return this.target;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FileStorageShareAcl defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String permission;
        private String target;
        public Builder() {}
        public Builder(FileStorageShareAcl defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.permission = defaults.permission;
    	      this.target = defaults.target;
        }

        @CustomType.Setter
        public Builder permission(String permission) {
            if (permission == null) {
              throw new MissingRequiredPropertyException("FileStorageShareAcl", "permission");
            }
            this.permission = permission;
            return this;
        }
        @CustomType.Setter
        public Builder target(String target) {
            if (target == null) {
              throw new MissingRequiredPropertyException("FileStorageShareAcl", "target");
            }
            this.target = target;
            return this;
        }
        public FileStorageShareAcl build() {
            final var _resultValue = new FileStorageShareAcl();
            _resultValue.permission = permission;
            _resultValue.target = target;
            return _resultValue;
        }
    }
}
