// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.upcloud.outputs.FileStorageShareAcl;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import javax.annotation.Nullable;

@CustomType
public final class FileStorageShare {
    /**
     * @return Access control entries (1–50).
     * 
     */
    private @Nullable List<FileStorageShareAcl> acls;
    /**
     * @return Unique name of the share (1–64 chars).
     * 
     */
    private String name;
    /**
     * @return Absolute path exported by the share (e.g. `/public`).
     * 
     */
    private String path;

    private FileStorageShare() {}
    /**
     * @return Access control entries (1–50).
     * 
     */
    public List<FileStorageShareAcl> acls() {
        return this.acls == null ? List.of() : this.acls;
    }
    /**
     * @return Unique name of the share (1–64 chars).
     * 
     */
    public String name() {
        return this.name;
    }
    /**
     * @return Absolute path exported by the share (e.g. `/public`).
     * 
     */
    public String path() {
        return this.path;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(FileStorageShare defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable List<FileStorageShareAcl> acls;
        private String name;
        private String path;
        public Builder() {}
        public Builder(FileStorageShare defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.acls = defaults.acls;
    	      this.name = defaults.name;
    	      this.path = defaults.path;
        }

        @CustomType.Setter
        public Builder acls(@Nullable List<FileStorageShareAcl> acls) {

            this.acls = acls;
            return this;
        }
        public Builder acls(FileStorageShareAcl... acls) {
            return acls(List.of(acls));
        }
        @CustomType.Setter
        public Builder name(String name) {
            if (name == null) {
              throw new MissingRequiredPropertyException("FileStorageShare", "name");
            }
            this.name = name;
            return this;
        }
        @CustomType.Setter
        public Builder path(String path) {
            if (path == null) {
              throw new MissingRequiredPropertyException("FileStorageShare", "path");
            }
            this.path = path;
            return this;
        }
        public FileStorageShare build() {
            final var _resultValue = new FileStorageShare();
            _resultValue.acls = acls;
            _resultValue.name = name;
            _resultValue.path = path;
            return _resultValue;
        }
    }
}
