// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.upcloud.outputs.GetManagedObjectStoragePoliciesPolicy;
import java.lang.String;
import java.util.List;
import java.util.Objects;

@CustomType
public final class GetManagedObjectStoragePoliciesResult {
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private List<GetManagedObjectStoragePoliciesPolicy> policies;
    private String serviceUuid;

    private GetManagedObjectStoragePoliciesResult() {}
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public List<GetManagedObjectStoragePoliciesPolicy> policies() {
        return this.policies;
    }
    public String serviceUuid() {
        return this.serviceUuid;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetManagedObjectStoragePoliciesResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private List<GetManagedObjectStoragePoliciesPolicy> policies;
        private String serviceUuid;
        public Builder() {}
        public Builder(GetManagedObjectStoragePoliciesResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.policies = defaults.policies;
    	      this.serviceUuid = defaults.serviceUuid;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetManagedObjectStoragePoliciesResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder policies(List<GetManagedObjectStoragePoliciesPolicy> policies) {
            if (policies == null) {
              throw new MissingRequiredPropertyException("GetManagedObjectStoragePoliciesResult", "policies");
            }
            this.policies = policies;
            return this;
        }
        public Builder policies(GetManagedObjectStoragePoliciesPolicy... policies) {
            return policies(List.of(policies));
        }
        @CustomType.Setter
        public Builder serviceUuid(String serviceUuid) {
            if (serviceUuid == null) {
              throw new MissingRequiredPropertyException("GetManagedObjectStoragePoliciesResult", "serviceUuid");
            }
            this.serviceUuid = serviceUuid;
            return this;
        }
        public GetManagedObjectStoragePoliciesResult build() {
            final var _resultValue = new GetManagedObjectStoragePoliciesResult();
            _resultValue.id = id;
            _resultValue.policies = policies;
            _resultValue.serviceUuid = serviceUuid;
            return _resultValue;
        }
    }
}
