// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.Boolean;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetServerNetworkInterfaceAdditionalIpAddress {
    /**
     * @return An additional IP address for this interface.
     * 
     */
    private String ipAddress;
    /**
     * @return The type of the additional IP address (`IPv4` or `IPv6`).
     * 
     */
    private String ipAddressFamily;
    /**
     * @return `true` indicates that the additional IP address is a floating IP address.
     * 
     */
    private Boolean ipAddressFloating;

    private GetServerNetworkInterfaceAdditionalIpAddress() {}
    /**
     * @return An additional IP address for this interface.
     * 
     */
    public String ipAddress() {
        return this.ipAddress;
    }
    /**
     * @return The type of the additional IP address (`IPv4` or `IPv6`).
     * 
     */
    public String ipAddressFamily() {
        return this.ipAddressFamily;
    }
    /**
     * @return `true` indicates that the additional IP address is a floating IP address.
     * 
     */
    public Boolean ipAddressFloating() {
        return this.ipAddressFloating;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetServerNetworkInterfaceAdditionalIpAddress defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String ipAddress;
        private String ipAddressFamily;
        private Boolean ipAddressFloating;
        public Builder() {}
        public Builder(GetServerNetworkInterfaceAdditionalIpAddress defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.ipAddress = defaults.ipAddress;
    	      this.ipAddressFamily = defaults.ipAddressFamily;
    	      this.ipAddressFloating = defaults.ipAddressFloating;
        }

        @CustomType.Setter
        public Builder ipAddress(String ipAddress) {
            if (ipAddress == null) {
              throw new MissingRequiredPropertyException("GetServerNetworkInterfaceAdditionalIpAddress", "ipAddress");
            }
            this.ipAddress = ipAddress;
            return this;
        }
        @CustomType.Setter
        public Builder ipAddressFamily(String ipAddressFamily) {
            if (ipAddressFamily == null) {
              throw new MissingRequiredPropertyException("GetServerNetworkInterfaceAdditionalIpAddress", "ipAddressFamily");
            }
            this.ipAddressFamily = ipAddressFamily;
            return this;
        }
        @CustomType.Setter
        public Builder ipAddressFloating(Boolean ipAddressFloating) {
            if (ipAddressFloating == null) {
              throw new MissingRequiredPropertyException("GetServerNetworkInterfaceAdditionalIpAddress", "ipAddressFloating");
            }
            this.ipAddressFloating = ipAddressFloating;
            return this;
        }
        public GetServerNetworkInterfaceAdditionalIpAddress build() {
            final var _resultValue = new GetServerNetworkInterfaceAdditionalIpAddress();
            _resultValue.ipAddress = ipAddress;
            _resultValue.ipAddressFamily = ipAddressFamily;
            _resultValue.ipAddressFloating = ipAddressFloating;
            return _resultValue;
        }
    }
}
