// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class LoadbalancerIpAddress {
    /**
     * @return Floating IP address to attach to the load balancer.
     * 
     */
    private String address;
    /**
     * @return Name of the network where to attach the IP address.
     * 
     */
    private String networkName;

    private LoadbalancerIpAddress() {}
    /**
     * @return Floating IP address to attach to the load balancer.
     * 
     */
    public String address() {
        return this.address;
    }
    /**
     * @return Name of the network where to attach the IP address.
     * 
     */
    public String networkName() {
        return this.networkName;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(LoadbalancerIpAddress defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String address;
        private String networkName;
        public Builder() {}
        public Builder(LoadbalancerIpAddress defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.address = defaults.address;
    	      this.networkName = defaults.networkName;
        }

        @CustomType.Setter
        public Builder address(String address) {
            if (address == null) {
              throw new MissingRequiredPropertyException("LoadbalancerIpAddress", "address");
            }
            this.address = address;
            return this;
        }
        @CustomType.Setter
        public Builder networkName(String networkName) {
            if (networkName == null) {
              throw new MissingRequiredPropertyException("LoadbalancerIpAddress", "networkName");
            }
            this.networkName = networkName;
            return this;
        }
        public LoadbalancerIpAddress build() {
            final var _resultValue = new LoadbalancerIpAddress();
            _resultValue.address = address;
            _resultValue.networkName = networkName;
            return _resultValue;
        }
    }
}
