// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.Boolean;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ManagedDatabaseOpensearchPropertiesJwt {
    /**
     * @return Enable or disable OpenSearch JWT authentication. Enables or disables JWT-based authentication for OpenSearch. When enabled, users can authenticate using JWT tokens.
     * 
     */
    private @Nullable Boolean enabled;
    /**
     * @return JWT clock skew tolerance in seconds. The maximum allowed time difference in seconds between the JWT issuer&#39;s clock and the OpenSearch server&#39;s clock. This helps prevent token validation failures due to minor time synchronization issues.
     * 
     */
    private @Nullable Integer jwtClockSkewToleranceSeconds;
    /**
     * @return HTTP header name for JWT token. The HTTP header name where the JWT token is transmitted. Typically &#39;Authorization&#39; for Bearer tokens.
     * 
     */
    private @Nullable String jwtHeader;
    /**
     * @return URL parameter name for JWT token. If the JWT token is transmitted as a URL parameter instead of an HTTP header, specify the parameter name here.
     * 
     */
    private @Nullable String jwtUrlParameter;
    /**
     * @return Required JWT audience. If specified, the JWT must contain an &#39;aud&#39; claim that matches this value. This provides additional security by ensuring the JWT was issued for the expected audience.
     * 
     */
    private @Nullable String requiredAudience;
    /**
     * @return Required JWT issuer. If specified, the JWT must contain an &#39;iss&#39; claim that matches this value. This provides additional security by ensuring the JWT was issued by the expected issuer.
     * 
     */
    private @Nullable String requiredIssuer;
    /**
     * @return JWT claim key for roles. The key in the JWT payload that contains the user&#39;s roles. If specified, roles will be extracted from the JWT for authorization.
     * 
     */
    private @Nullable String rolesKey;
    /**
     * @return JWT signing key. The secret key used to sign and verify JWT tokens. This should be a secure, randomly generated key HMAC key or public RSA/ECDSA key.
     * 
     */
    private @Nullable String signingKey;
    /**
     * @return JWT claim key for subject. The key in the JWT payload that contains the user&#39;s subject identifier. If not specified, the &#39;sub&#39; claim is used by default.
     * 
     */
    private @Nullable String subjectKey;

    private ManagedDatabaseOpensearchPropertiesJwt() {}
    /**
     * @return Enable or disable OpenSearch JWT authentication. Enables or disables JWT-based authentication for OpenSearch. When enabled, users can authenticate using JWT tokens.
     * 
     */
    public Optional<Boolean> enabled() {
        return Optional.ofNullable(this.enabled);
    }
    /**
     * @return JWT clock skew tolerance in seconds. The maximum allowed time difference in seconds between the JWT issuer&#39;s clock and the OpenSearch server&#39;s clock. This helps prevent token validation failures due to minor time synchronization issues.
     * 
     */
    public Optional<Integer> jwtClockSkewToleranceSeconds() {
        return Optional.ofNullable(this.jwtClockSkewToleranceSeconds);
    }
    /**
     * @return HTTP header name for JWT token. The HTTP header name where the JWT token is transmitted. Typically &#39;Authorization&#39; for Bearer tokens.
     * 
     */
    public Optional<String> jwtHeader() {
        return Optional.ofNullable(this.jwtHeader);
    }
    /**
     * @return URL parameter name for JWT token. If the JWT token is transmitted as a URL parameter instead of an HTTP header, specify the parameter name here.
     * 
     */
    public Optional<String> jwtUrlParameter() {
        return Optional.ofNullable(this.jwtUrlParameter);
    }
    /**
     * @return Required JWT audience. If specified, the JWT must contain an &#39;aud&#39; claim that matches this value. This provides additional security by ensuring the JWT was issued for the expected audience.
     * 
     */
    public Optional<String> requiredAudience() {
        return Optional.ofNullable(this.requiredAudience);
    }
    /**
     * @return Required JWT issuer. If specified, the JWT must contain an &#39;iss&#39; claim that matches this value. This provides additional security by ensuring the JWT was issued by the expected issuer.
     * 
     */
    public Optional<String> requiredIssuer() {
        return Optional.ofNullable(this.requiredIssuer);
    }
    /**
     * @return JWT claim key for roles. The key in the JWT payload that contains the user&#39;s roles. If specified, roles will be extracted from the JWT for authorization.
     * 
     */
    public Optional<String> rolesKey() {
        return Optional.ofNullable(this.rolesKey);
    }
    /**
     * @return JWT signing key. The secret key used to sign and verify JWT tokens. This should be a secure, randomly generated key HMAC key or public RSA/ECDSA key.
     * 
     */
    public Optional<String> signingKey() {
        return Optional.ofNullable(this.signingKey);
    }
    /**
     * @return JWT claim key for subject. The key in the JWT payload that contains the user&#39;s subject identifier. If not specified, the &#39;sub&#39; claim is used by default.
     * 
     */
    public Optional<String> subjectKey() {
        return Optional.ofNullable(this.subjectKey);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ManagedDatabaseOpensearchPropertiesJwt defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable Boolean enabled;
        private @Nullable Integer jwtClockSkewToleranceSeconds;
        private @Nullable String jwtHeader;
        private @Nullable String jwtUrlParameter;
        private @Nullable String requiredAudience;
        private @Nullable String requiredIssuer;
        private @Nullable String rolesKey;
        private @Nullable String signingKey;
        private @Nullable String subjectKey;
        public Builder() {}
        public Builder(ManagedDatabaseOpensearchPropertiesJwt defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.enabled = defaults.enabled;
    	      this.jwtClockSkewToleranceSeconds = defaults.jwtClockSkewToleranceSeconds;
    	      this.jwtHeader = defaults.jwtHeader;
    	      this.jwtUrlParameter = defaults.jwtUrlParameter;
    	      this.requiredAudience = defaults.requiredAudience;
    	      this.requiredIssuer = defaults.requiredIssuer;
    	      this.rolesKey = defaults.rolesKey;
    	      this.signingKey = defaults.signingKey;
    	      this.subjectKey = defaults.subjectKey;
        }

        @CustomType.Setter
        public Builder enabled(@Nullable Boolean enabled) {

            this.enabled = enabled;
            return this;
        }
        @CustomType.Setter
        public Builder jwtClockSkewToleranceSeconds(@Nullable Integer jwtClockSkewToleranceSeconds) {

            this.jwtClockSkewToleranceSeconds = jwtClockSkewToleranceSeconds;
            return this;
        }
        @CustomType.Setter
        public Builder jwtHeader(@Nullable String jwtHeader) {

            this.jwtHeader = jwtHeader;
            return this;
        }
        @CustomType.Setter
        public Builder jwtUrlParameter(@Nullable String jwtUrlParameter) {

            this.jwtUrlParameter = jwtUrlParameter;
            return this;
        }
        @CustomType.Setter
        public Builder requiredAudience(@Nullable String requiredAudience) {

            this.requiredAudience = requiredAudience;
            return this;
        }
        @CustomType.Setter
        public Builder requiredIssuer(@Nullable String requiredIssuer) {

            this.requiredIssuer = requiredIssuer;
            return this;
        }
        @CustomType.Setter
        public Builder rolesKey(@Nullable String rolesKey) {

            this.rolesKey = rolesKey;
            return this;
        }
        @CustomType.Setter
        public Builder signingKey(@Nullable String signingKey) {

            this.signingKey = signingKey;
            return this;
        }
        @CustomType.Setter
        public Builder subjectKey(@Nullable String subjectKey) {

            this.subjectKey = subjectKey;
            return this;
        }
        public ManagedDatabaseOpensearchPropertiesJwt build() {
            final var _resultValue = new ManagedDatabaseOpensearchPropertiesJwt();
            _resultValue.enabled = enabled;
            _resultValue.jwtClockSkewToleranceSeconds = jwtClockSkewToleranceSeconds;
            _resultValue.jwtHeader = jwtHeader;
            _resultValue.jwtUrlParameter = jwtUrlParameter;
            _resultValue.requiredAudience = requiredAudience;
            _resultValue.requiredIssuer = requiredIssuer;
            _resultValue.rolesKey = rolesKey;
            _resultValue.signingKey = signingKey;
            _resultValue.subjectKey = subjectKey;
            return _resultValue;
        }
    }
}
