// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;

@CustomType
public final class ManagedDatabaseUserValkeyAccessControl {
    /**
     * @return Set access control to all commands in specified categories.
     * 
     */
    private @Nullable String categories;
    /**
     * @return Set access control to Pub/Sub channels.
     * 
     */
    private @Nullable String channels;
    /**
     * @return Set access control to commands.
     * 
     */
    private @Nullable String commands;
    /**
     * @return Set access control to keys.
     * 
     */
    private @Nullable String keys;

    private ManagedDatabaseUserValkeyAccessControl() {}
    /**
     * @return Set access control to all commands in specified categories.
     * 
     */
    public Optional<String> categories() {
        return Optional.ofNullable(this.categories);
    }
    /**
     * @return Set access control to Pub/Sub channels.
     * 
     */
    public Optional<String> channels() {
        return Optional.ofNullable(this.channels);
    }
    /**
     * @return Set access control to commands.
     * 
     */
    public Optional<String> commands() {
        return Optional.ofNullable(this.commands);
    }
    /**
     * @return Set access control to keys.
     * 
     */
    public Optional<String> keys() {
        return Optional.ofNullable(this.keys);
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(ManagedDatabaseUserValkeyAccessControl defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private @Nullable String categories;
        private @Nullable String channels;
        private @Nullable String commands;
        private @Nullable String keys;
        public Builder() {}
        public Builder(ManagedDatabaseUserValkeyAccessControl defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.categories = defaults.categories;
    	      this.channels = defaults.channels;
    	      this.commands = defaults.commands;
    	      this.keys = defaults.keys;
        }

        @CustomType.Setter
        public Builder categories(@Nullable String categories) {

            this.categories = categories;
            return this;
        }
        @CustomType.Setter
        public Builder channels(@Nullable String channels) {

            this.channels = channels;
            return this;
        }
        @CustomType.Setter
        public Builder commands(@Nullable String commands) {

            this.commands = commands;
            return this;
        }
        @CustomType.Setter
        public Builder keys(@Nullable String keys) {

            this.keys = keys;
            return this;
        }
        public ManagedDatabaseUserValkeyAccessControl build() {
            final var _resultValue = new ManagedDatabaseUserValkeyAccessControl();
            _resultValue.categories = categories;
            _resultValue.channels = channels;
            _resultValue.commands = commands;
            _resultValue.keys = keys;
            return _resultValue;
        }
    }
}
