// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class NetworkPeeringPeerNetwork {
    /**
     * @return The UUID of the network.
     * 
     */
    private String uuid;

    private NetworkPeeringPeerNetwork() {}
    /**
     * @return The UUID of the network.
     * 
     */
    public String uuid() {
        return this.uuid;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(NetworkPeeringPeerNetwork defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String uuid;
        public Builder() {}
        public Builder(NetworkPeeringPeerNetwork defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.uuid = defaults.uuid;
        }

        @CustomType.Setter
        public Builder uuid(String uuid) {
            if (uuid == null) {
              throw new MissingRequiredPropertyException("NetworkPeeringPeerNetwork", "uuid");
            }
            this.uuid = uuid;
            return this;
        }
        public NetworkPeeringPeerNetwork build() {
            final var _resultValue = new NetworkPeeringPeerNetwork();
            _resultValue.uuid = uuid;
            return _resultValue;
        }
    }
}
