// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Upcloud
{
    public static class GetHosts
    {
        /// <summary>
        /// Returns a list of available UpCloud hosts. 
        /// 		A host identifies the host server that virtual machines are run on. 
        /// 		Only hosts on private cloud to which the calling account has access to are available through this resource.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Upcloud = Pulumi.Upcloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var allHosts = Upcloud.GetHosts.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Task<GetHostsResult> InvokeAsync(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.InvokeAsync<GetHostsResult>("upcloud:index/getHosts:getHosts", InvokeArgs.Empty, options.WithDefaults());

        /// <summary>
        /// Returns a list of available UpCloud hosts. 
        /// 		A host identifies the host server that virtual machines are run on. 
        /// 		Only hosts on private cloud to which the calling account has access to are available through this resource.
        /// 
        /// ## Example Usage
        /// 
        /// ```csharp
        /// using System.Collections.Generic;
        /// using System.Linq;
        /// using Pulumi;
        /// using Upcloud = Pulumi.Upcloud;
        /// 
        /// return await Deployment.RunAsync(() =&gt; 
        /// {
        ///     var allHosts = Upcloud.GetHosts.Invoke();
        /// 
        /// });
        /// ```
        /// </summary>
        public static Output<GetHostsResult> Invoke(InvokeOptions? options = null)
            => global::Pulumi.Deployment.Instance.Invoke<GetHostsResult>("upcloud:index/getHosts:getHosts", InvokeArgs.Empty, options.WithDefaults());
    }


    [OutputType]
    public sealed class GetHostsResult
    {
        public readonly ImmutableArray<Outputs.GetHostsHostResult> Hosts;
        /// <summary>
        /// The provider-assigned unique ID for this managed resource.
        /// </summary>
        public readonly string Id;

        [OutputConstructor]
        private GetHostsResult(
            ImmutableArray<Outputs.GetHostsHostResult> hosts,

            string id)
        {
            Hosts = hosts;
            Id = id;
        }
    }
}
