// *** WARNING: this file was generated by pulumi-language-dotnet. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;
using Pulumi;

namespace UpCloud.Pulumi.UpCloud.Outputs
{

    [OutputType]
    public sealed class LoadbalancerFrontendRuleMatchersHost
    {
        /// <summary>
        /// Defines if the condition should be inverted. Works similarly to logical NOT operator.
        /// </summary>
        public readonly bool? Inverse;
        /// <summary>
        /// String value.
        /// </summary>
        public readonly string Value;

        [OutputConstructor]
        private LoadbalancerFrontendRuleMatchersHost(
            bool? inverse,

            string value)
        {
            Inverse = inverse;
            Value = value;
        }
    }
}
