// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Export;
import com.pulumi.core.annotations.ResourceType;
import com.pulumi.core.internal.Codegen;
import com.pulumi.upcloud.FileStorageShareAclArgs;
import com.pulumi.upcloud.Utilities;
import com.pulumi.upcloud.inputs.FileStorageShareAclState;
import java.lang.String;
import javax.annotation.Nullable;

/**
 * This resource represents a File Storage Share ACL entry.
 * 
 */
@ResourceType(type="upcloud:index/fileStorageShareAcl:FileStorageShareAcl")
public class FileStorageShareAcl extends com.pulumi.resources.CustomResource {
    /**
     * UUID of the file storage service.
     * 
     */
    @Export(name="fileStorage", refs={String.class}, tree="[0]")
    private Output<String> fileStorage;

    /**
     * @return UUID of the file storage service.
     * 
     */
    public Output<String> fileStorage() {
        return this.fileStorage;
    }
    /**
     * Unique name of the ACL entry (1–64 chars).
     * 
     */
    @Export(name="name", refs={String.class}, tree="[0]")
    private Output<String> name;

    /**
     * @return Unique name of the ACL entry (1–64 chars).
     * 
     */
    public Output<String> name() {
        return this.name;
    }
    /**
     * Access level: &#39;ro&#39; or &#39;rw&#39;.
     * 
     */
    @Export(name="permission", refs={String.class}, tree="[0]")
    private Output<String> permission;

    /**
     * @return Access level: &#39;ro&#39; or &#39;rw&#39;.
     * 
     */
    public Output<String> permission() {
        return this.permission;
    }
    /**
     * Name of the share.
     * 
     */
    @Export(name="shareName", refs={String.class}, tree="[0]")
    private Output<String> shareName;

    /**
     * @return Name of the share.
     * 
     */
    public Output<String> shareName() {
        return this.shareName;
    }
    /**
     * Target IP/CIDR or &#39;*&#39;.
     * 
     */
    @Export(name="target", refs={String.class}, tree="[0]")
    private Output<String> target;

    /**
     * @return Target IP/CIDR or &#39;*&#39;.
     * 
     */
    public Output<String> target() {
        return this.target;
    }

    /**
     *
     * @param name The _unique_ name of the resulting resource.
     */
    public FileStorageShareAcl(java.lang.String name) {
        this(name, FileStorageShareAclArgs.Empty);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     */
    public FileStorageShareAcl(java.lang.String name, FileStorageShareAclArgs args) {
        this(name, args, null);
    }
    /**
     *
     * @param name The _unique_ name of the resulting resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param options A bag of options that control this resource's behavior.
     */
    public FileStorageShareAcl(java.lang.String name, FileStorageShareAclArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("upcloud:index/fileStorageShareAcl:FileStorageShareAcl", name, makeArgs(args, options), makeResourceOptions(options, Codegen.empty()), false);
    }

    private FileStorageShareAcl(java.lang.String name, Output<java.lang.String> id, @Nullable FileStorageShareAclState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        super("upcloud:index/fileStorageShareAcl:FileStorageShareAcl", name, state, makeResourceOptions(options, id), false);
    }

    private static FileStorageShareAclArgs makeArgs(FileStorageShareAclArgs args, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        if (options != null && options.getUrn().isPresent()) {
            return null;
        }
        return args == null ? FileStorageShareAclArgs.Empty : args;
    }

    private static com.pulumi.resources.CustomResourceOptions makeResourceOptions(@Nullable com.pulumi.resources.CustomResourceOptions options, @Nullable Output<java.lang.String> id) {
        var defaultOptions = com.pulumi.resources.CustomResourceOptions.builder()
            .version(Utilities.getVersion())
            .pluginDownloadURL("github://api.github.com/UpCloudLtd/pulumi-upcloud")
            .build();
        return com.pulumi.resources.CustomResourceOptions.merge(defaultOptions, options, id);
    }

    /**
     * Get an existing Host resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state
     * @param options Optional settings to control the behavior of the CustomResource.
     */
    public static FileStorageShareAcl get(java.lang.String name, Output<java.lang.String> id, @Nullable FileStorageShareAclState state, @Nullable com.pulumi.resources.CustomResourceOptions options) {
        return new FileStorageShareAcl(name, id, state, options);
    }
}
