// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ManagedDatabaseLogicalDatabaseArgs extends com.pulumi.resources.ResourceArgs {

    public static final ManagedDatabaseLogicalDatabaseArgs Empty = new ManagedDatabaseLogicalDatabaseArgs();

    /**
     * Default character set for the database (LC_CTYPE)
     * 
     */
    @Import(name="characterSet")
    private @Nullable Output<String> characterSet;

    /**
     * @return Default character set for the database (LC_CTYPE)
     * 
     */
    public Optional<Output<String>> characterSet() {
        return Optional.ofNullable(this.characterSet);
    }

    /**
     * Default collation for the database (LC_COLLATE)
     * 
     */
    @Import(name="collation")
    private @Nullable Output<String> collation;

    /**
     * @return Default collation for the database (LC_COLLATE)
     * 
     */
    public Optional<Output<String>> collation() {
        return Optional.ofNullable(this.collation);
    }

    /**
     * Name of the logical database
     * 
     */
    @Import(name="name")
    private @Nullable Output<String> name;

    /**
     * @return Name of the logical database
     * 
     */
    public Optional<Output<String>> name() {
        return Optional.ofNullable(this.name);
    }

    /**
     * Service&#39;s UUID for which this user belongs to
     * 
     */
    @Import(name="service", required=true)
    private Output<String> service;

    /**
     * @return Service&#39;s UUID for which this user belongs to
     * 
     */
    public Output<String> service() {
        return this.service;
    }

    private ManagedDatabaseLogicalDatabaseArgs() {}

    private ManagedDatabaseLogicalDatabaseArgs(ManagedDatabaseLogicalDatabaseArgs $) {
        this.characterSet = $.characterSet;
        this.collation = $.collation;
        this.name = $.name;
        this.service = $.service;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ManagedDatabaseLogicalDatabaseArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ManagedDatabaseLogicalDatabaseArgs $;

        public Builder() {
            $ = new ManagedDatabaseLogicalDatabaseArgs();
        }

        public Builder(ManagedDatabaseLogicalDatabaseArgs defaults) {
            $ = new ManagedDatabaseLogicalDatabaseArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param characterSet Default character set for the database (LC_CTYPE)
         * 
         * @return builder
         * 
         */
        public Builder characterSet(@Nullable Output<String> characterSet) {
            $.characterSet = characterSet;
            return this;
        }

        /**
         * @param characterSet Default character set for the database (LC_CTYPE)
         * 
         * @return builder
         * 
         */
        public Builder characterSet(String characterSet) {
            return characterSet(Output.of(characterSet));
        }

        /**
         * @param collation Default collation for the database (LC_COLLATE)
         * 
         * @return builder
         * 
         */
        public Builder collation(@Nullable Output<String> collation) {
            $.collation = collation;
            return this;
        }

        /**
         * @param collation Default collation for the database (LC_COLLATE)
         * 
         * @return builder
         * 
         */
        public Builder collation(String collation) {
            return collation(Output.of(collation));
        }

        /**
         * @param name Name of the logical database
         * 
         * @return builder
         * 
         */
        public Builder name(@Nullable Output<String> name) {
            $.name = name;
            return this;
        }

        /**
         * @param name Name of the logical database
         * 
         * @return builder
         * 
         */
        public Builder name(String name) {
            return name(Output.of(name));
        }

        /**
         * @param service Service&#39;s UUID for which this user belongs to
         * 
         * @return builder
         * 
         */
        public Builder service(Output<String> service) {
            $.service = service;
            return this;
        }

        /**
         * @param service Service&#39;s UUID for which this user belongs to
         * 
         * @return builder
         * 
         */
        public Builder service(String service) {
            return service(Output.of(service));
        }

        public ManagedDatabaseLogicalDatabaseArgs build() {
            if ($.service == null) {
                throw new MissingRequiredPropertyException("ManagedDatabaseLogicalDatabaseArgs", "service");
            }
            return $;
        }
    }

}
