// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GatewayConnectionTunnelIpsecAuthPskArgs extends com.pulumi.resources.ResourceArgs {

    public static final GatewayConnectionTunnelIpsecAuthPskArgs Empty = new GatewayConnectionTunnelIpsecAuthPskArgs();

    /**
     * The pre-shared key. This value is only used during resource creation and is not returned in the state. It is not possible to update this value. If you need to update it, delete the connection and create a new one.
     * 
     */
    @Import(name="psk", required=true)
    private Output<String> psk;

    /**
     * @return The pre-shared key. This value is only used during resource creation and is not returned in the state. It is not possible to update this value. If you need to update it, delete the connection and create a new one.
     * 
     */
    public Output<String> psk() {
        return this.psk;
    }

    private GatewayConnectionTunnelIpsecAuthPskArgs() {}

    private GatewayConnectionTunnelIpsecAuthPskArgs(GatewayConnectionTunnelIpsecAuthPskArgs $) {
        this.psk = $.psk;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GatewayConnectionTunnelIpsecAuthPskArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GatewayConnectionTunnelIpsecAuthPskArgs $;

        public Builder() {
            $ = new GatewayConnectionTunnelIpsecAuthPskArgs();
        }

        public Builder(GatewayConnectionTunnelIpsecAuthPskArgs defaults) {
            $ = new GatewayConnectionTunnelIpsecAuthPskArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param psk The pre-shared key. This value is only used during resource creation and is not returned in the state. It is not possible to update this value. If you need to update it, delete the connection and create a new one.
         * 
         * @return builder
         * 
         */
        public Builder psk(Output<String> psk) {
            $.psk = psk;
            return this;
        }

        /**
         * @param psk The pre-shared key. This value is only used during resource creation and is not returned in the state. It is not possible to update this value. If you need to update it, delete the connection and create a new one.
         * 
         * @return builder
         * 
         */
        public Builder psk(String psk) {
            return psk(Output.of(psk));
        }

        public GatewayConnectionTunnelIpsecAuthPskArgs build() {
            if ($.psk == null) {
                throw new MissingRequiredPropertyException("GatewayConnectionTunnelIpsecAuthPskArgs", "psk");
            }
            return $;
        }
    }

}
