// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.upcloud.inputs.GetHostsHost;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetHostsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetHostsPlainArgs Empty = new GetHostsPlainArgs();

    @Import(name="hosts")
    private @Nullable List<GetHostsHost> hosts;

    public Optional<List<GetHostsHost>> hosts() {
        return Optional.ofNullable(this.hosts);
    }

    private GetHostsPlainArgs() {}

    private GetHostsPlainArgs(GetHostsPlainArgs $) {
        this.hosts = $.hosts;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetHostsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetHostsPlainArgs $;

        public Builder() {
            $ = new GetHostsPlainArgs();
        }

        public Builder(GetHostsPlainArgs defaults) {
            $ = new GetHostsPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder hosts(@Nullable List<GetHostsHost> hosts) {
            $.hosts = hosts;
            return this;
        }

        public Builder hosts(GetHostsHost... hosts) {
            return hosts(List.of(hosts));
        }

        public GetHostsPlainArgs build() {
            return $;
        }
    }

}
