// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.upcloud.inputs.GetManagedDatabaseValkeySessionsSession;
import java.lang.Integer;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetManagedDatabaseValkeySessionsPlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetManagedDatabaseValkeySessionsPlainArgs Empty = new GetManagedDatabaseValkeySessionsPlainArgs();

    @Import(name="limit")
    private @Nullable Integer limit;

    public Optional<Integer> limit() {
        return Optional.ofNullable(this.limit);
    }

    @Import(name="offset")
    private @Nullable Integer offset;

    public Optional<Integer> offset() {
        return Optional.ofNullable(this.offset);
    }

    @Import(name="order")
    private @Nullable String order;

    public Optional<String> order() {
        return Optional.ofNullable(this.order);
    }

    @Import(name="service", required=true)
    private String service;

    public String service() {
        return this.service;
    }

    @Import(name="sessions")
    private @Nullable List<GetManagedDatabaseValkeySessionsSession> sessions;

    public Optional<List<GetManagedDatabaseValkeySessionsSession>> sessions() {
        return Optional.ofNullable(this.sessions);
    }

    private GetManagedDatabaseValkeySessionsPlainArgs() {}

    private GetManagedDatabaseValkeySessionsPlainArgs(GetManagedDatabaseValkeySessionsPlainArgs $) {
        this.limit = $.limit;
        this.offset = $.offset;
        this.order = $.order;
        this.service = $.service;
        this.sessions = $.sessions;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetManagedDatabaseValkeySessionsPlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetManagedDatabaseValkeySessionsPlainArgs $;

        public Builder() {
            $ = new GetManagedDatabaseValkeySessionsPlainArgs();
        }

        public Builder(GetManagedDatabaseValkeySessionsPlainArgs defaults) {
            $ = new GetManagedDatabaseValkeySessionsPlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder limit(@Nullable Integer limit) {
            $.limit = limit;
            return this;
        }

        public Builder offset(@Nullable Integer offset) {
            $.offset = offset;
            return this;
        }

        public Builder order(@Nullable String order) {
            $.order = order;
            return this;
        }

        public Builder service(String service) {
            $.service = service;
            return this;
        }

        public Builder sessions(@Nullable List<GetManagedDatabaseValkeySessionsSession> sessions) {
            $.sessions = sessions;
            return this;
        }

        public Builder sessions(GetManagedDatabaseValkeySessionsSession... sessions) {
            return sessions(List.of(sessions));
        }

        public GetManagedDatabaseValkeySessionsPlainArgs build() {
            if ($.service == null) {
                throw new MissingRequiredPropertyException("GetManagedDatabaseValkeySessionsPlainArgs", "service");
            }
            return $;
        }
    }

}
