// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.upcloud.inputs.GetManagedObjectStorageRegionsRegionArgs;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetManagedObjectStorageRegionsArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetManagedObjectStorageRegionsArgs Empty = new GetManagedObjectStorageRegionsArgs();

    @Import(name="regions")
    private @Nullable Output<List<GetManagedObjectStorageRegionsRegionArgs>> regions;

    public Optional<Output<List<GetManagedObjectStorageRegionsRegionArgs>>> regions() {
        return Optional.ofNullable(this.regions);
    }

    private GetManagedObjectStorageRegionsArgs() {}

    private GetManagedObjectStorageRegionsArgs(GetManagedObjectStorageRegionsArgs $) {
        this.regions = $.regions;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetManagedObjectStorageRegionsArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetManagedObjectStorageRegionsArgs $;

        public Builder() {
            $ = new GetManagedObjectStorageRegionsArgs();
        }

        public Builder(GetManagedObjectStorageRegionsArgs defaults) {
            $ = new GetManagedObjectStorageRegionsArgs(Objects.requireNonNull(defaults));
        }

        public Builder regions(@Nullable Output<List<GetManagedObjectStorageRegionsRegionArgs>> regions) {
            $.regions = regions;
            return this;
        }

        public Builder regions(List<GetManagedObjectStorageRegionsRegionArgs> regions) {
            return regions(Output.of(regions));
        }

        public Builder regions(GetManagedObjectStorageRegionsRegionArgs... regions) {
            return regions(List.of(regions));
        }

        public GetManagedObjectStorageRegionsArgs build() {
            return $;
        }
    }

}
