// *** WARNING: this file was generated by pulumi-language-java. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import com.pulumi.upcloud.inputs.GetManagedDatabaseOpensearchIndicesIndexArgs;
import java.lang.String;
import java.util.List;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class GetManagedDatabaseOpensearchIndicesArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetManagedDatabaseOpensearchIndicesArgs Empty = new GetManagedDatabaseOpensearchIndicesArgs();

    @Import(name="indices")
    private @Nullable Output<List<GetManagedDatabaseOpensearchIndicesIndexArgs>> indices;

    public Optional<Output<List<GetManagedDatabaseOpensearchIndicesIndexArgs>>> indices() {
        return Optional.ofNullable(this.indices);
    }

    @Import(name="service", required=true)
    private Output<String> service;

    public Output<String> service() {
        return this.service;
    }

    private GetManagedDatabaseOpensearchIndicesArgs() {}

    private GetManagedDatabaseOpensearchIndicesArgs(GetManagedDatabaseOpensearchIndicesArgs $) {
        this.indices = $.indices;
        this.service = $.service;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetManagedDatabaseOpensearchIndicesArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetManagedDatabaseOpensearchIndicesArgs $;

        public Builder() {
            $ = new GetManagedDatabaseOpensearchIndicesArgs();
        }

        public Builder(GetManagedDatabaseOpensearchIndicesArgs defaults) {
            $ = new GetManagedDatabaseOpensearchIndicesArgs(Objects.requireNonNull(defaults));
        }

        public Builder indices(@Nullable Output<List<GetManagedDatabaseOpensearchIndicesIndexArgs>> indices) {
            $.indices = indices;
            return this;
        }

        public Builder indices(List<GetManagedDatabaseOpensearchIndicesIndexArgs> indices) {
            return indices(Output.of(indices));
        }

        public Builder indices(GetManagedDatabaseOpensearchIndicesIndexArgs... indices) {
            return indices(List.of(indices));
        }

        public Builder service(Output<String> service) {
            $.service = service;
            return this;
        }

        public Builder service(String service) {
            return service(Output.of(service));
        }

        public GetManagedDatabaseOpensearchIndicesArgs build() {
            if ($.service == null) {
                throw new MissingRequiredPropertyException("GetManagedDatabaseOpensearchIndicesArgs", "service");
            }
            return $;
        }
    }

}
