// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import java.lang.Integer;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class KubernetesNodeGroupCloudNativePlanArgs extends com.pulumi.resources.ResourceArgs {

    public static final KubernetesNodeGroupCloudNativePlanArgs Empty = new KubernetesNodeGroupCloudNativePlanArgs();

    /**
     * The size of the storage device in gigabytes.
     * 
     */
    @Import(name="storageSize")
    private @Nullable Output<Integer> storageSize;

    /**
     * @return The size of the storage device in gigabytes.
     * 
     */
    public Optional<Output<Integer>> storageSize() {
        return Optional.ofNullable(this.storageSize);
    }

    /**
     * The storage tier to use.
     * 
     */
    @Import(name="storageTier")
    private @Nullable Output<String> storageTier;

    /**
     * @return The storage tier to use.
     * 
     */
    public Optional<Output<String>> storageTier() {
        return Optional.ofNullable(this.storageTier);
    }

    private KubernetesNodeGroupCloudNativePlanArgs() {}

    private KubernetesNodeGroupCloudNativePlanArgs(KubernetesNodeGroupCloudNativePlanArgs $) {
        this.storageSize = $.storageSize;
        this.storageTier = $.storageTier;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(KubernetesNodeGroupCloudNativePlanArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private KubernetesNodeGroupCloudNativePlanArgs $;

        public Builder() {
            $ = new KubernetesNodeGroupCloudNativePlanArgs();
        }

        public Builder(KubernetesNodeGroupCloudNativePlanArgs defaults) {
            $ = new KubernetesNodeGroupCloudNativePlanArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param storageSize The size of the storage device in gigabytes.
         * 
         * @return builder
         * 
         */
        public Builder storageSize(@Nullable Output<Integer> storageSize) {
            $.storageSize = storageSize;
            return this;
        }

        /**
         * @param storageSize The size of the storage device in gigabytes.
         * 
         * @return builder
         * 
         */
        public Builder storageSize(Integer storageSize) {
            return storageSize(Output.of(storageSize));
        }

        /**
         * @param storageTier The storage tier to use.
         * 
         * @return builder
         * 
         */
        public Builder storageTier(@Nullable Output<String> storageTier) {
            $.storageTier = storageTier;
            return this;
        }

        /**
         * @param storageTier The storage tier to use.
         * 
         * @return builder
         * 
         */
        public Builder storageTier(String storageTier) {
            return storageTier(Output.of(storageTier));
        }

        public KubernetesNodeGroupCloudNativePlanArgs build() {
            return $;
        }
    }

}
