// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.upcloud.inputs;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class ManagedDatabaseUserOpensearchAccessControlRuleArgs extends com.pulumi.resources.ResourceArgs {

    public static final ManagedDatabaseUserOpensearchAccessControlRuleArgs Empty = new ManagedDatabaseUserOpensearchAccessControlRuleArgs();

    /**
     * Set index name, pattern or top level API.
     * 
     */
    @Import(name="index", required=true)
    private Output<String> index;

    /**
     * @return Set index name, pattern or top level API.
     * 
     */
    public Output<String> index() {
        return this.index;
    }

    /**
     * Set permission access.
     * 
     */
    @Import(name="permission", required=true)
    private Output<String> permission;

    /**
     * @return Set permission access.
     * 
     */
    public Output<String> permission() {
        return this.permission;
    }

    private ManagedDatabaseUserOpensearchAccessControlRuleArgs() {}

    private ManagedDatabaseUserOpensearchAccessControlRuleArgs(ManagedDatabaseUserOpensearchAccessControlRuleArgs $) {
        this.index = $.index;
        this.permission = $.permission;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ManagedDatabaseUserOpensearchAccessControlRuleArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ManagedDatabaseUserOpensearchAccessControlRuleArgs $;

        public Builder() {
            $ = new ManagedDatabaseUserOpensearchAccessControlRuleArgs();
        }

        public Builder(ManagedDatabaseUserOpensearchAccessControlRuleArgs defaults) {
            $ = new ManagedDatabaseUserOpensearchAccessControlRuleArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param index Set index name, pattern or top level API.
         * 
         * @return builder
         * 
         */
        public Builder index(Output<String> index) {
            $.index = index;
            return this;
        }

        /**
         * @param index Set index name, pattern or top level API.
         * 
         * @return builder
         * 
         */
        public Builder index(String index) {
            return index(Output.of(index));
        }

        /**
         * @param permission Set permission access.
         * 
         * @return builder
         * 
         */
        public Builder permission(Output<String> permission) {
            $.permission = permission;
            return this;
        }

        /**
         * @param permission Set permission access.
         * 
         * @return builder
         * 
         */
        public Builder permission(String permission) {
            return permission(Output.of(permission));
        }

        public ManagedDatabaseUserOpensearchAccessControlRuleArgs build() {
            if ($.index == null) {
                throw new MissingRequiredPropertyException("ManagedDatabaseUserOpensearchAccessControlRuleArgs", "index");
            }
            if ($.permission == null) {
                throw new MissingRequiredPropertyException("ManagedDatabaseUserOpensearchAccessControlRuleArgs", "permission");
            }
            return $;
        }
    }

}
