// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Threading.Tasks;
using Pulumi.Serialization;

namespace Pulumi.Upcloud.Inputs
{

    public sealed class ManagedDatabaseOpensearchPropertiesAuthFailureListenersArgs : global::Pulumi.ResourceArgs
    {
        [Input("internalAuthenticationBackendLimiting")]
        public Input<Inputs.ManagedDatabaseOpensearchPropertiesAuthFailureListenersInternalAuthenticationBackendLimitingArgs>? InternalAuthenticationBackendLimiting { get; set; }

        /// <summary>
        /// IP address rate limiting settings.
        /// </summary>
        [Input("ipRateLimiting")]
        public Input<Inputs.ManagedDatabaseOpensearchPropertiesAuthFailureListenersIpRateLimitingArgs>? IpRateLimiting { get; set; }

        public ManagedDatabaseOpensearchPropertiesAuthFailureListenersArgs()
        {
        }
        public static new ManagedDatabaseOpensearchPropertiesAuthFailureListenersArgs Empty => new ManagedDatabaseOpensearchPropertiesAuthFailureListenersArgs();
    }
}
