// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

/**
 * Data-source is deprecated.
 */
export function getTags(opts?: pulumi.InvokeOptions): Promise<GetTagsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("upcloud:index/getTags:getTags", {
    }, opts);
}

/**
 * A collection of values returned by getTags.
 */
export interface GetTagsResult {
    /**
     * The provider-assigned unique ID for this managed resource.
     */
    readonly id: string;
    readonly tags: outputs.GetTagsTag[];
}
/**
 * Data-source is deprecated.
 */
export function getTagsOutput(opts?: pulumi.InvokeOutputOptions): pulumi.Output<GetTagsResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("upcloud:index/getTags:getTags", {
    }, opts);
}
